USE [SMILE]
GO

/****** Object:  Table [dbo].[SavedOpportunities] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SavedOpportunities](
	[SaveID] [int] IDENTITY(1,1) NOT NULL,
	[StuID] [int] NOT NULL,
	[OppID] [int] NOT NULL,
	[DateSaved] [datetime] NULL DEFAULT (getdate()),
PRIMARY KEY CLUSTERED 
(
	[SaveID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_Saved_Student_Opp] UNIQUE NONCLUSTERED 
(
	[StuID] ASC,
	[OppID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SavedOpportunities]  WITH CHECK ADD  CONSTRAINT [FK_Saved_Stu] FOREIGN KEY([StuID])
REFERENCES [dbo].[Student] ([StuID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[SavedOpportunities] CHECK CONSTRAINT [FK_Saved_Stu]
GO

ALTER TABLE [dbo].[SavedOpportunities]  WITH CHECK ADD  CONSTRAINT [FK_Saved_Opp] FOREIGN KEY([OppID])
REFERENCES [dbo].[Opportunities] ([OppID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[SavedOpportunities] CHECK CONSTRAINT [FK_Saved_Opp]
GO
